export const SUBMIT_PLACE_TYPE = 'SUBMIT_PLACE_TYPE';
export const SUBMIT_BEDROOMS = 'SUBMIT_BEDROOMS';
export const SUBMIT_BATHROOMS = 'SUBMIT_BATHROOMS';
export const SUBMIT_LOCATION = 'SUBMIT_LOCATION';
export const SUBMIT_LISTING = 'SUBMIT_LISTING';
export const SUBMIT_LISTING_SUCCESS = 'SUBMIT_LISTING';
export const SUBMIT_LISTING_ERROR = 'SUBMIT_LISTING';


